controller:
  ingress:
    enabled: true
    hosts:
      - jenkins.your-domain.com
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
  
  additionalPlugins:
    - sonar:latest
    - artifactory:latest
    - pipeline-utility-steps:latest
  
  # Enable JNLP port
  jenkinsAdminEmail: "admin@example.com"
  
  # Service configuration to expose JNLP port
  serviceType: ClusterIP
  servicePort: 8080
  targetPort: 8080
  # JNLP port configuration
  agentListenerPort: 50000
  
  # Resources for the controller
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"
  
  # Persistence configuration
  persistence:
    enabled: true
    size: "10Gi"