pipeline {
    agent any

    stages {
        stage("Checkout") {
            steps {
                git branch: 'main', url: 'https://github.com/gatmbarz123/NodeFunctions.git'
            }
        }

        stage("Read and Print"){
            steps{
                script{
                    def Readfile = readFile file: "data.json"
                    def jsonFile = readJSON file: Readfile

                    jsonFile.each{ key,value ->
                        echo $"{key}" ':' $"{value}"

                    }
                }
            }
        }
    }
}
