def cuildConfig =  readYaml file: 'build-config.yaml'

pipeline{
    agent any

    stages{
        stage('Build for test '){
            steps{
                script{
                    buildConfig.steps.each [steps ->
                        stage(step.name){
                            sh step.command 
                        }
                    ]
                }
            }
        }
    }

}