pipeline {
    agent any

    stages {
        stage("Checkout") {
            steps {
                git branch: 'main', url: 'https://github.com/gatmbarz123/NodeFunctions.git'
            }
        }

        stage("Read File") {
            steps {
                script {
                    buildConfig = readYaml file: 'test_problems/build-config.yaml'
                }
            }
        }

        stage('Build for Test') {
            steps {
                script {
                    buildConfig.steps.each { step ->
                        echo "Running step: ${step.name}"
                        sh step.command
                    }
                }
            }
        }
    }
}
